<?php
    return [
        'user_menu' => 'User',
        'assets_menu' => 'Assets',
        'setting_menu' => 'Setting',
        'salary_menu' => 'Salary',
        'salary_increment_menu' => "Salary Increment",
        'document_type_menu' => "Document Type",
        'document_menu' => "Document",
        'expense_menu' => 'Expense',
        'revenue_menu' => 'Revenue',
        'hr_manager_menu' => 'HR Management',
        'employee_menu' => 'Employee Management',
        'counter_menu' => 'Counter',
        'public_holiday_menu' => 'Public Holiday',
        'attendance_menu' => 'Attendance',
        'change_request_menu' => "Change Request",
        'reports_menu' => 'Reports',
        'salary_slip_menu' => 'Salary Slip',
        'leave_request_menu'=> 'Leave Request',
        'employee_overtime_menu' => 'Employee Overtime',
        'social_media_post_menu' => 'Social Media Posts',

        'user_sub_menu'=> 'Users',
        'user_role_sub_menu'=> 'User role',
        'asset_type_sub_menu'=> 'Asset Type',
        'supplier_sub_menu'=> 'Supplier',
        'brand_sub_menu'=> 'Brand',
        'asset_master_sub_menu'=> 'Asset Master',
        'asset_allocation_sub_menu'=> 'Asset Allocation',
        'type_sub_menu' => 'Expense Type',
        'branch_sub_menu' => 'Branch',
        'manager_sub_menu' => 'Manager',
        'technology_sub_menu' => 'Technology',
        'designation_sub_menu' => 'Designation',
        'latter_template_sub_menu' => 'Latter Template',
        'latter_abbreviation_sub_menu' =>  'Latter Abbreviation',
        'salary_sub_menu' => 'Salary',
        'salary_increment_sub_menu' => 'Salary Increment',
        'document_type_sub_menu' => 'Document Type',
        'document_sub_menu' => 'Document',
        'expense_sub_menu' => 'Expense',
        'revenue_sub_menu' => 'Revenue',
        'hr_income_sub_menu' => 'Hr Income',
        'hr_expense_sub_menu' => 'Hr Expense',
        'employee_sub_menu' => 'Employee',
        'counter_sub_menu' => 'Counter',
        'attendance_sub_menu' => 'Attendance',
        'change_request_sub_menu' => 'Change Request',
        'expense_report_sub_menu' => 'Expense Report',
        'revenue_report_sub_menu' => 'Revenue Report',
        'salary_report_sub_menu' => 'Salary Report',
        'profit_loss_sub_menu' => 'Profit Loss Report',
        'counter_sheet_sub_menu' => 'Counter Sheet',
        'public_holiday_sub_menu' => 'Public Holiday',
        'employee_birthday_sub_menu' => 'Employee Birthday',
        'employee_bond_last_date_sub_menu' => 'Employee Bond Last Date',
        'salary_slip_sub_menu' => 'Salary Slip',
        'leave_request_sub_menu' => 'Leave Request',
        'employee_overtime_sub_menu' => 'Employee Overtime',
        'social_media_post_sub_menu' => 'Social Media Posts',

        'interview_menu' => 'Interview',
        'interview_sub_menu' => 'Interview',
    ];

?>
